### ISSUE TITLE
Setup navigation system

### ISSUE THREAD

**Issue by Inunor** [Inunor/internship#10]
You will have different "pages", something like the home page, login page, and so on. Every page will include its own components, services, styles. You don't want to load all code at once: for that angular has a routing system and specifically **lazy loading pages**. 
So, you will have some root `app.routing.module` and this module will have information about these lazy loaded modules to load (I think there will be links in the header or something like that)
Your main component will look something like that:
```
<app-header></app-header>
<router-outlet></router-outlet>
<app-footer></app-footer>
```
_router-outlet_ is a placeholder for your routing lazy modules pages (which you described in an app.routing.module)

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FE/ Setup Navigation system](https://trello.com/c/P2qie6Wq/19-fe-setup-navigation-system)
