### ISSUE TITLE
Create user info modal dialog

### ISSUE THREAD

**Issue by ivankuznetsov96dev** [Inunor/internship#37]
Create user info modal dialog. Use https://material.angular.io/components/dialog/overview
and
https://material.angular.io/components/card/overview
material UI

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create user info modal dialog](https://trello.com/c/ITwKEWHd/24-create-user-info-modal-dialog)
