### ISSUE TITLE
Create basic mockups for the project

### ISSUE THREAD

**Issue by Inunor** [Inunor/internship#4]
Don't spend too much time on it. I think one day will be enough
You don't need to draw fully detailed mockups, just some simple boxes, and lines

Something like that, I would say even simplier
![basic-mockup](https://user-images.githubusercontent.com/35798617/124349064-fa6f4a00-dbf5-11eb-8816-4a660d0ae4f8.jpg)

**Comment by shuliakleonid** [comment]
link to [mockups](https://miro.com/welcomeonboard/NmFwbzJnUEdyRTVOUktlYkVxUFJSV0xpWDVQVjRzdjhBT1I3QTJSdUJ4TmQ3S0E4a28xSGRDVUtXSE4yQkN1NnwzMDc0NDU3MzQ4ODEyNzk0MzQz)

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create basic mockups for the project](https://trello.com/c/nYuPZ3AI/56-create-basic-mockups-for-the-project)
