### ISSUE TITLE
Add components to writing test module

### ISSUE THREAD

**Issue by HannaZakhlebayeva** [Inunor/internship#51]

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add components to writing test module](https://trello.com/c/WeELjhoc/27-add-components-to-writing-test-module)

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add pagination](https://trello.com/c/ZCvob6X4/60-add-pagination)
