### ISSUE TITLE
Create modal window component

### ISSUE THREAD

**Issue by ExxZzyy** [Inunor/internship#54]

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd Tasks](https://trello.com/c/2DqeegD1/14-frontend-tasks)

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Modal Winfdow component](https://trello.com/c/92gSDhi5/28-create-modal-winfdow-component)
