### ISSUE TITLE
Angular intruduction

### ISSUE THREAD

**Issue by Inunor** [Inunor/internship#8]
Links

1. Try id guide (basic angular application) https://angular.io/start
2. After that during the internship you should read the Understanding angular section step by step. Angular documentation is huge, but in my opinion, it's great, because you actually don't need another learning source. Just read their guides and explore API

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FE/ Angular introduction](https://trello.com/c/O0wbeXlR/17-fe-angular-introduction)
